package ntwk:theater;

interface message-server-client {
    use types.{json, event};

    handle-send: func(msg: json, state: json) -> json;
    handle-request: func(msg: json, state: json) -> tuple<json, json>;
}

interface message-server-host {
    use types.{json, actor-id};

    // send and forget message
    send: func(actor-id: actor-id, msg: json) -> result<_, string>;

    // send message and wait for response
    request: func(actor-id: actor-id, msg: json) -> result<json, string>;
}
