package ntwk:theater;

// Define a shared type for messages
interface types {
    /// Generic message type as bytes that can be serialized/deserialized
    type json = list<u8>;
    type state = list<u8>;

    type actor-id = string;

    record chain {
        events: list<meta-event>
    }

    record meta-event {
        hash: u64,
        event: event,
    }

    record event {
        event-type: string,
        parent: option<u64>,
        data: json,
    }
}
